version: '3.6'

# https://graspingtech.com/docker-compose-postgresql/

services: 
    gamestrackerdb:
        image: postgres:latest
        container_name: gamestrackerdb
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecret
            - APP_DB_USER=docker
            - APP_DB_PASS=docker
            - APP_DB_NAME=gamestrackerdb
        ports:
            - 5432:5432
        volumes:
            - ./init.sh:/docker-entrypoint-initdb.d/init.sh
            - ./init.sql:/tmp/init.sql